// Code generated by "stringer -type=ColorSpaceKHR"; DO NOT EDIT.

package vk

import "strconv"

const _ColorSpaceKHR_name = "COLOR_SPACE_SRGB_NONLINEAR_KHR"

var _ColorSpaceKHR_index = [...]uint8{0, 30}

func (i ColorSpaceKHR) String() string {
	if i >= ColorSpaceKHR(len(_ColorSpaceKHR_index)-1) {
		return "ColorSpaceKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ColorSpaceKHR_name[_ColorSpaceKHR_index[i]:_ColorSpaceKHR_index[i+1]]
}
