// Code generated by "stringer -type=ComponentSwizzle"; DO NOT EDIT.

package vk

import "strconv"

const _ComponentSwizzle_name = "ComponentSwizzleIdentityComponentSwizzleZeroComponentSwizzleOneComponentSwizzleRComponentSwizzleGComponentSwizzleBComponentSwizzleA"

var _ComponentSwizzle_index = [...]uint8{0, 24, 44, 63, 80, 97, 114, 131}

func (i ComponentSwizzle) String() string {
	if i >= ComponentSwizzle(len(_ComponentSwizzle_index)-1) {
		return "ComponentSwizzle(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ComponentSwizzle_name[_ComponentSwizzle_index[i]:_ComponentSwizzle_index[i+1]]
}
