package vk

// #cgo pkg-config: vulkan
// #cgo CFLAGS: -DVK_NO_PROTOTYPES
// #include <vulkan/vulkan_core.h>
import "C"
import (
	"strconv"
	"strings"
)

type DeviceQueueCreateFlags C.VkDeviceQueueCreateFlags
type QueueFlags C.VkQueueFlags
type PhysicalDeviceType C.VkPhysicalDeviceType
type Result C.VkResult
type StructureType C.VkStructureType
type SurfaceTransformFlagsKHR C.VkSurfaceTransformFlagsKHR
type CompositeAlphaFlagsKHR C.VkCompositeAlphaFlagsKHR
type ImageUsageFlags C.VkImageUsageFlags
type Format C.VkFormat
type ColorSpaceKHR C.VkColorSpaceKHR
type PresentModeKHR C.VkPresentModeKHR

const (
	DEVICE_QUEUE_CREATE_PROTECTED_BIT DeviceQueueCreateFlags = C.VK_DEVICE_QUEUE_CREATE_PROTECTED_BIT
)

const (
	QUEUE_GRAPHICS_BIT       QueueFlags = C.VK_QUEUE_GRAPHICS_BIT
	QUEUE_COMPUTE_BIT        QueueFlags = C.VK_QUEUE_COMPUTE_BIT
	QUEUE_TRANSFER_BIT       QueueFlags = C.VK_QUEUE_TRANSFER_BIT
	QUEUE_SPARSE_BINDING_BIT QueueFlags = C.VK_QUEUE_SPARSE_BINDING_BIT
	QUEUE_PROTECTED_BIT      QueueFlags = C.VK_QUEUE_PROTECTED_BIT
)

const (
	PHYSICAL_DEVICE_TYPE_OTHER          PhysicalDeviceType = C.VK_PHYSICAL_DEVICE_TYPE_OTHER
	PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU PhysicalDeviceType = C.VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
	PHYSICAL_DEVICE_TYPE_DISCRETE_GPU   PhysicalDeviceType = C.VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
	PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU    PhysicalDeviceType = C.VK_PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU
	PHYSICAL_DEVICE_TYPE_CPU            PhysicalDeviceType = C.VK_PHYSICAL_DEVICE_TYPE_CPU
)

const (
	SUCCESS                        Result = C.VK_SUCCESS
	NOT_READY                      Result = C.VK_NOT_READY
	TIMEOUT                        Result = C.VK_TIMEOUT
	EVENT_SET                      Result = C.VK_EVENT_SET
	EVENT_RESET                    Result = C.VK_EVENT_RESET
	INCOMPLETE                     Result = C.VK_INCOMPLETE
	ERROR_OUT_OF_HOST_MEMORY       Result = C.VK_ERROR_OUT_OF_HOST_MEMORY
	ERROR_OUT_OF_DEVICE_MEMORY     Result = C.VK_ERROR_OUT_OF_DEVICE_MEMORY
	ERROR_INITIALIZATION_FAILED    Result = C.VK_ERROR_INITIALIZATION_FAILED
	ERROR_DEVICE_LOST              Result = C.VK_ERROR_DEVICE_LOST
	ERROR_MEMORY_MAP_FAILED        Result = C.VK_ERROR_MEMORY_MAP_FAILED
	ERROR_LAYER_NOT_PRESENT        Result = C.VK_ERROR_LAYER_NOT_PRESENT
	ERROR_EXTENSION_NOT_PRESENT    Result = C.VK_ERROR_EXTENSION_NOT_PRESENT
	ERROR_FEATURE_NOT_PRESENT      Result = C.VK_ERROR_FEATURE_NOT_PRESENT
	ERROR_INCOMPATIBLE_DRIVER      Result = C.VK_ERROR_INCOMPATIBLE_DRIVER
	ERROR_TOO_MANY_OBJECTS         Result = C.VK_ERROR_TOO_MANY_OBJECTS
	ERROR_FORMAT_NOT_SUPPORTED     Result = C.VK_ERROR_FORMAT_NOT_SUPPORTED
	ERROR_FRAGMENTED_POOL          Result = C.VK_ERROR_FRAGMENTED_POOL
	ERROR_OUT_OF_POOL_MEMORY       Result = C.VK_ERROR_OUT_OF_POOL_MEMORY
	ERROR_INVALID_EXTERNAL_HANDLE  Result = C.VK_ERROR_INVALID_EXTERNAL_HANDLE
	ERROR_SURFACE_LOST_KHR         Result = C.VK_ERROR_SURFACE_LOST_KHR
	ERROR_NATIVE_WINDOW_IN_USE_KHR Result = C.VK_ERROR_NATIVE_WINDOW_IN_USE_KHR
	SUBOPTIMAL_KHR                 Result = C.VK_SUBOPTIMAL_KHR
	ERROR_OUT_OF_DATE_KHR          Result = C.VK_ERROR_OUT_OF_DATE_KHR
	ERROR_INCOMPATIBLE_DISPLAY_KHR Result = C.VK_ERROR_INCOMPATIBLE_DISPLAY_KHR
	ERROR_VALIDATION_FAILED_EXT    Result = C.VK_ERROR_VALIDATION_FAILED_EXT
	ERROR_INVALID_SHADER_NV        Result = C.VK_ERROR_INVALID_SHADER_NV
	// VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT = C.VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT
	ERROR_FRAGMENTATION_EXT           Result = C.VK_ERROR_FRAGMENTATION_EXT
	ERROR_NOT_PERMITTED_EXT           Result = C.VK_ERROR_NOT_PERMITTED_EXT
	ERROR_OUT_OF_POOL_MEMORY_KHR      Result = C.VK_ERROR_OUT_OF_POOL_MEMORY_KHR
	ERROR_INVALID_EXTERNAL_HANDLE_KHR Result = C.VK_ERROR_INVALID_EXTERNAL_HANDLE_KHR
)

const (
	STRUCTURE_TYPE_APPLICATION_INFO                                             = C.VK_STRUCTURE_TYPE_APPLICATION_INFO
	STRUCTURE_TYPE_INSTANCE_CREATE_INFO                                         = C.VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO
	STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO                                     = C.VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO
	STRUCTURE_TYPE_DEVICE_CREATE_INFO                                           = C.VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO
	STRUCTURE_TYPE_SUBMIT_INFO                                                  = C.VK_STRUCTURE_TYPE_SUBMIT_INFO
	STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO                                         = C.VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO
	STRUCTURE_TYPE_MAPPED_MEMORY_RANGE                                          = C.VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE
	STRUCTURE_TYPE_BIND_SPARSE_INFO                                             = C.VK_STRUCTURE_TYPE_BIND_SPARSE_INFO
	STRUCTURE_TYPE_FENCE_CREATE_INFO                                            = C.VK_STRUCTURE_TYPE_FENCE_CREATE_INFO
	STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO                                        = C.VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO
	STRUCTURE_TYPE_EVENT_CREATE_INFO                                            = C.VK_STRUCTURE_TYPE_EVENT_CREATE_INFO
	STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO                                       = C.VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO
	STRUCTURE_TYPE_BUFFER_CREATE_INFO                                           = C.VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO
	STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO                                      = C.VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO
	STRUCTURE_TYPE_IMAGE_CREATE_INFO                                            = C.VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO
	STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO                                       = C.VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO
	STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO                                    = C.VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO
	STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO                                   = C.VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO
	STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO                            = C.VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO
	STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO                      = C.VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO
	STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO                    = C.VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO
	STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO                      = C.VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO
	STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO                          = C.VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO
	STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO                     = C.VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO
	STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO                       = C.VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
	STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO                     = C.VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO
	STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO                       = C.VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO
	STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO                           = C.VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO
	STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO                                = C.VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO
	STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO                                 = C.VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO
	STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO                                  = C.VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO
	STRUCTURE_TYPE_SAMPLER_CREATE_INFO                                          = C.VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO
	STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO                            = C.VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO
	STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO                                  = C.VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO
	STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO                                 = C.VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO
	STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET                                         = C.VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET
	STRUCTURE_TYPE_COPY_DESCRIPTOR_SET                                          = C.VK_STRUCTURE_TYPE_COPY_DESCRIPTOR_SET
	STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO                                      = C.VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO
	STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO                                      = C.VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO
	STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO                                     = C.VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO
	STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO                                 = C.VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO
	STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_INFO                              = C.VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_INFO
	STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO                                    = C.VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO
	STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO                                       = C.VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO
	STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER                                        = C.VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER
	STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER                                         = C.VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER
	STRUCTURE_TYPE_MEMORY_BARRIER                                               = C.VK_STRUCTURE_TYPE_MEMORY_BARRIER
	STRUCTURE_TYPE_LOADER_INSTANCE_CREATE_INFO                                  = C.VK_STRUCTURE_TYPE_LOADER_INSTANCE_CREATE_INFO
	STRUCTURE_TYPE_LOADER_DEVICE_CREATE_INFO                                    = C.VK_STRUCTURE_TYPE_LOADER_DEVICE_CREATE_INFO
	STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_PROPERTIES                          = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_PROPERTIES
	STRUCTURE_TYPE_BIND_BUFFER_MEMORY_INFO                                      = C.VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_INFO
	STRUCTURE_TYPE_BIND_IMAGE_MEMORY_INFO                                       = C.VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_INFO
	STRUCTURE_TYPE_PHYSICAL_DEVICE_16BIT_STORAGE_FEATURES                       = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_16BIT_STORAGE_FEATURES
	STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS                                = C.VK_STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS
	STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO                               = C.VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO
	STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO                                   = C.VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO
	STRUCTURE_TYPE_DEVICE_GROUP_RENDER_PASS_BEGIN_INFO                          = C.VK_STRUCTURE_TYPE_DEVICE_GROUP_RENDER_PASS_BEGIN_INFO
	STRUCTURE_TYPE_DEVICE_GROUP_COMMAND_BUFFER_BEGIN_INFO                       = C.VK_STRUCTURE_TYPE_DEVICE_GROUP_COMMAND_BUFFER_BEGIN_INFO
	STRUCTURE_TYPE_DEVICE_GROUP_SUBMIT_INFO                                     = C.VK_STRUCTURE_TYPE_DEVICE_GROUP_SUBMIT_INFO
	STRUCTURE_TYPE_DEVICE_GROUP_BIND_SPARSE_INFO                                = C.VK_STRUCTURE_TYPE_DEVICE_GROUP_BIND_SPARSE_INFO
	STRUCTURE_TYPE_BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO                         = C.VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO
	STRUCTURE_TYPE_BIND_IMAGE_MEMORY_DEVICE_GROUP_INFO                          = C.VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_DEVICE_GROUP_INFO
	STRUCTURE_TYPE_PHYSICAL_DEVICE_GROUP_PROPERTIES                             = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GROUP_PROPERTIES
	STRUCTURE_TYPE_DEVICE_GROUP_DEVICE_CREATE_INFO                              = C.VK_STRUCTURE_TYPE_DEVICE_GROUP_DEVICE_CREATE_INFO
	STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2                            = C.VK_STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2
	STRUCTURE_TYPE_IMAGE_MEMORY_REQUIREMENTS_INFO_2                             = C.VK_STRUCTURE_TYPE_IMAGE_MEMORY_REQUIREMENTS_INFO_2
	STRUCTURE_TYPE_IMAGE_SPARSE_MEMORY_REQUIREMENTS_INFO_2                      = C.VK_STRUCTURE_TYPE_IMAGE_SPARSE_MEMORY_REQUIREMENTS_INFO_2
	STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2                                        = C.VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2
	STRUCTURE_TYPE_SPARSE_IMAGE_MEMORY_REQUIREMENTS_2                           = C.VK_STRUCTURE_TYPE_SPARSE_IMAGE_MEMORY_REQUIREMENTS_2
	STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2                                   = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2
	STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2                                 = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2
	STRUCTURE_TYPE_FORMAT_PROPERTIES_2                                          = C.VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_2
	STRUCTURE_TYPE_IMAGE_FORMAT_PROPERTIES_2                                    = C.VK_STRUCTURE_TYPE_IMAGE_FORMAT_PROPERTIES_2
	STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2                          = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2
	STRUCTURE_TYPE_QUEUE_FAMILY_PROPERTIES_2                                    = C.VK_STRUCTURE_TYPE_QUEUE_FAMILY_PROPERTIES_2
	STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_PROPERTIES_2                          = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_PROPERTIES_2
	STRUCTURE_TYPE_SPARSE_IMAGE_FORMAT_PROPERTIES_2                             = C.VK_STRUCTURE_TYPE_SPARSE_IMAGE_FORMAT_PROPERTIES_2
	STRUCTURE_TYPE_PHYSICAL_DEVICE_SPARSE_IMAGE_FORMAT_INFO_2                   = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SPARSE_IMAGE_FORMAT_INFO_2
	STRUCTURE_TYPE_PHYSICAL_DEVICE_POINT_CLIPPING_PROPERTIES                    = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_POINT_CLIPPING_PROPERTIES
	STRUCTURE_TYPE_RENDER_PASS_INPUT_ATTACHMENT_ASPECT_CREATE_INFO              = C.VK_STRUCTURE_TYPE_RENDER_PASS_INPUT_ATTACHMENT_ASPECT_CREATE_INFO
	STRUCTURE_TYPE_IMAGE_VIEW_USAGE_CREATE_INFO                                 = C.VK_STRUCTURE_TYPE_IMAGE_VIEW_USAGE_CREATE_INFO
	STRUCTURE_TYPE_PIPELINE_TESSELLATION_DOMAIN_ORIGIN_STATE_CREATE_INFO        = C.VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_DOMAIN_ORIGIN_STATE_CREATE_INFO
	STRUCTURE_TYPE_RENDER_PASS_MULTIVIEW_CREATE_INFO                            = C.VK_STRUCTURE_TYPE_RENDER_PASS_MULTIVIEW_CREATE_INFO
	STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_FEATURES                           = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_FEATURES
	STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PROPERTIES                         = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PROPERTIES
	STRUCTURE_TYPE_PHYSICAL_DEVICE_VARIABLE_POINTER_FEATURES                    = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VARIABLE_POINTER_FEATURES
	STRUCTURE_TYPE_PROTECTED_SUBMIT_INFO                                        = C.VK_STRUCTURE_TYPE_PROTECTED_SUBMIT_INFO
	STRUCTURE_TYPE_PHYSICAL_DEVICE_PROTECTED_MEMORY_FEATURES                    = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROTECTED_MEMORY_FEATURES
	STRUCTURE_TYPE_PHYSICAL_DEVICE_PROTECTED_MEMORY_PROPERTIES                  = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROTECTED_MEMORY_PROPERTIES
	STRUCTURE_TYPE_DEVICE_QUEUE_INFO_2                                          = C.VK_STRUCTURE_TYPE_DEVICE_QUEUE_INFO_2
	STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO                         = C.VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO
	STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO                                = C.VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO
	STRUCTURE_TYPE_BIND_IMAGE_PLANE_MEMORY_INFO                                 = C.VK_STRUCTURE_TYPE_BIND_IMAGE_PLANE_MEMORY_INFO
	STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO                         = C.VK_STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO
	STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES            = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES
	STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES             = C.VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES
	STRUCTURE_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_CREATE_INFO                       = C.VK_STRUCTURE_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_CREATE_INFO
	STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_IMAGE_FORMAT_INFO                   = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_IMAGE_FORMAT_INFO
	STRUCTURE_TYPE_EXTERNAL_IMAGE_FORMAT_PROPERTIES                             = C.VK_STRUCTURE_TYPE_EXTERNAL_IMAGE_FORMAT_PROPERTIES
	STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_BUFFER_INFO                         = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_BUFFER_INFO
	STRUCTURE_TYPE_EXTERNAL_BUFFER_PROPERTIES                                   = C.VK_STRUCTURE_TYPE_EXTERNAL_BUFFER_PROPERTIES
	STRUCTURE_TYPE_PHYSICAL_DEVICE_ID_PROPERTIES                                = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ID_PROPERTIES
	STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO                           = C.VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO
	STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO                            = C.VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO
	STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO                                  = C.VK_STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO
	STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_FENCE_INFO                          = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_FENCE_INFO
	STRUCTURE_TYPE_EXTERNAL_FENCE_PROPERTIES                                    = C.VK_STRUCTURE_TYPE_EXTERNAL_FENCE_PROPERTIES
	STRUCTURE_TYPE_EXPORT_FENCE_CREATE_INFO                                     = C.VK_STRUCTURE_TYPE_EXPORT_FENCE_CREATE_INFO
	STRUCTURE_TYPE_EXPORT_SEMAPHORE_CREATE_INFO                                 = C.VK_STRUCTURE_TYPE_EXPORT_SEMAPHORE_CREATE_INFO
	STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_SEMAPHORE_INFO                      = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_SEMAPHORE_INFO
	STRUCTURE_TYPE_EXTERNAL_SEMAPHORE_PROPERTIES                                = C.VK_STRUCTURE_TYPE_EXTERNAL_SEMAPHORE_PROPERTIES
	STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_3_PROPERTIES                     = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_3_PROPERTIES
	STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_SUPPORT                                = C.VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_SUPPORT
	STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_DRAW_PARAMETER_FEATURES               = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_DRAW_PARAMETER_FEATURES
	STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR                                    = C.VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR
	STRUCTURE_TYPE_PRESENT_INFO_KHR                                             = C.VK_STRUCTURE_TYPE_PRESENT_INFO_KHR
	STRUCTURE_TYPE_DEVICE_GROUP_PRESENT_CAPABILITIES_KHR                        = C.VK_STRUCTURE_TYPE_DEVICE_GROUP_PRESENT_CAPABILITIES_KHR
	STRUCTURE_TYPE_IMAGE_SWAPCHAIN_CREATE_INFO_KHR                              = C.VK_STRUCTURE_TYPE_IMAGE_SWAPCHAIN_CREATE_INFO_KHR
	STRUCTURE_TYPE_BIND_IMAGE_MEMORY_SWAPCHAIN_INFO_KHR                         = C.VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_SWAPCHAIN_INFO_KHR
	STRUCTURE_TYPE_ACQUIRE_NEXT_IMAGE_INFO_KHR                                  = C.VK_STRUCTURE_TYPE_ACQUIRE_NEXT_IMAGE_INFO_KHR
	STRUCTURE_TYPE_DEVICE_GROUP_PRESENT_INFO_KHR                                = C.VK_STRUCTURE_TYPE_DEVICE_GROUP_PRESENT_INFO_KHR
	STRUCTURE_TYPE_DEVICE_GROUP_SWAPCHAIN_CREATE_INFO_KHR                       = C.VK_STRUCTURE_TYPE_DEVICE_GROUP_SWAPCHAIN_CREATE_INFO_KHR
	STRUCTURE_TYPE_DISPLAY_MODE_CREATE_INFO_KHR                                 = C.VK_STRUCTURE_TYPE_DISPLAY_MODE_CREATE_INFO_KHR
	STRUCTURE_TYPE_DISPLAY_SURFACE_CREATE_INFO_KHR                              = C.VK_STRUCTURE_TYPE_DISPLAY_SURFACE_CREATE_INFO_KHR
	STRUCTURE_TYPE_DISPLAY_PRESENT_INFO_KHR                                     = C.VK_STRUCTURE_TYPE_DISPLAY_PRESENT_INFO_KHR
	STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR                                 = C.VK_STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR
	STRUCTURE_TYPE_XCB_SURFACE_CREATE_INFO_KHR                                  = C.VK_STRUCTURE_TYPE_XCB_SURFACE_CREATE_INFO_KHR
	STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR                              = C.VK_STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR
	STRUCTURE_TYPE_MIR_SURFACE_CREATE_INFO_KHR                                  = C.VK_STRUCTURE_TYPE_MIR_SURFACE_CREATE_INFO_KHR
	STRUCTURE_TYPE_ANDROID_SURFACE_CREATE_INFO_KHR                              = C.VK_STRUCTURE_TYPE_ANDROID_SURFACE_CREATE_INFO_KHR
	STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR                                = C.VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR
	STRUCTURE_TYPE_DEBUG_REPORT_CALLBACK_CREATE_INFO_EXT                        = C.VK_STRUCTURE_TYPE_DEBUG_REPORT_CALLBACK_CREATE_INFO_EXT
	STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_RASTERIZATION_ORDER_AMD         = C.VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_RASTERIZATION_ORDER_AMD
	STRUCTURE_TYPE_DEBUG_MARKER_OBJECT_NAME_INFO_EXT                            = C.VK_STRUCTURE_TYPE_DEBUG_MARKER_OBJECT_NAME_INFO_EXT
	STRUCTURE_TYPE_DEBUG_MARKER_OBJECT_TAG_INFO_EXT                             = C.VK_STRUCTURE_TYPE_DEBUG_MARKER_OBJECT_TAG_INFO_EXT
	STRUCTURE_TYPE_DEBUG_MARKER_MARKER_INFO_EXT                                 = C.VK_STRUCTURE_TYPE_DEBUG_MARKER_MARKER_INFO_EXT
	STRUCTURE_TYPE_DEDICATED_ALLOCATION_IMAGE_CREATE_INFO_NV                    = C.VK_STRUCTURE_TYPE_DEDICATED_ALLOCATION_IMAGE_CREATE_INFO_NV
	STRUCTURE_TYPE_DEDICATED_ALLOCATION_BUFFER_CREATE_INFO_NV                   = C.VK_STRUCTURE_TYPE_DEDICATED_ALLOCATION_BUFFER_CREATE_INFO_NV
	STRUCTURE_TYPE_DEDICATED_ALLOCATION_MEMORY_ALLOCATE_INFO_NV                 = C.VK_STRUCTURE_TYPE_DEDICATED_ALLOCATION_MEMORY_ALLOCATE_INFO_NV
	STRUCTURE_TYPE_TEXTURE_LOD_GATHER_FORMAT_PROPERTIES_AMD                     = C.VK_STRUCTURE_TYPE_TEXTURE_LOD_GATHER_FORMAT_PROPERTIES_AMD
	STRUCTURE_TYPE_PHYSICAL_DEVICE_CORNER_SAMPLED_IMAGE_FEATURES_NV             = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CORNER_SAMPLED_IMAGE_FEATURES_NV
	STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO_NV                         = C.VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO_NV
	STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO_NV                               = C.VK_STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO_NV
	STRUCTURE_TYPE_IMPORT_MEMORY_WIN32_HANDLE_INFO_NV                           = C.VK_STRUCTURE_TYPE_IMPORT_MEMORY_WIN32_HANDLE_INFO_NV
	STRUCTURE_TYPE_EXPORT_MEMORY_WIN32_HANDLE_INFO_NV                           = C.VK_STRUCTURE_TYPE_EXPORT_MEMORY_WIN32_HANDLE_INFO_NV
	STRUCTURE_TYPE_WIN32_KEYED_MUTEX_ACQUIRE_RELEASE_INFO_NV                    = C.VK_STRUCTURE_TYPE_WIN32_KEYED_MUTEX_ACQUIRE_RELEASE_INFO_NV
	STRUCTURE_TYPE_VALIDATION_FLAGS_EXT                                         = C.VK_STRUCTURE_TYPE_VALIDATION_FLAGS_EXT
	STRUCTURE_TYPE_VI_SURFACE_CREATE_INFO_NN                                    = C.VK_STRUCTURE_TYPE_VI_SURFACE_CREATE_INFO_NN
	STRUCTURE_TYPE_IMAGE_VIEW_ASTC_DECODE_MODE_EXT                              = C.VK_STRUCTURE_TYPE_IMAGE_VIEW_ASTC_DECODE_MODE_EXT
	STRUCTURE_TYPE_PHYSICAL_DEVICE_ASTC_DECODE_FEATURES_EXT                     = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ASTC_DECODE_FEATURES_EXT
	STRUCTURE_TYPE_IMPORT_MEMORY_WIN32_HANDLE_INFO_KHR                          = C.VK_STRUCTURE_TYPE_IMPORT_MEMORY_WIN32_HANDLE_INFO_KHR
	STRUCTURE_TYPE_EXPORT_MEMORY_WIN32_HANDLE_INFO_KHR                          = C.VK_STRUCTURE_TYPE_EXPORT_MEMORY_WIN32_HANDLE_INFO_KHR
	STRUCTURE_TYPE_MEMORY_WIN32_HANDLE_PROPERTIES_KHR                           = C.VK_STRUCTURE_TYPE_MEMORY_WIN32_HANDLE_PROPERTIES_KHR
	STRUCTURE_TYPE_MEMORY_GET_WIN32_HANDLE_INFO_KHR                             = C.VK_STRUCTURE_TYPE_MEMORY_GET_WIN32_HANDLE_INFO_KHR
	STRUCTURE_TYPE_IMPORT_MEMORY_FD_INFO_KHR                                    = C.VK_STRUCTURE_TYPE_IMPORT_MEMORY_FD_INFO_KHR
	STRUCTURE_TYPE_MEMORY_FD_PROPERTIES_KHR                                     = C.VK_STRUCTURE_TYPE_MEMORY_FD_PROPERTIES_KHR
	STRUCTURE_TYPE_MEMORY_GET_FD_INFO_KHR                                       = C.VK_STRUCTURE_TYPE_MEMORY_GET_FD_INFO_KHR
	STRUCTURE_TYPE_WIN32_KEYED_MUTEX_ACQUIRE_RELEASE_INFO_KHR                   = C.VK_STRUCTURE_TYPE_WIN32_KEYED_MUTEX_ACQUIRE_RELEASE_INFO_KHR
	STRUCTURE_TYPE_IMPORT_SEMAPHORE_WIN32_HANDLE_INFO_KHR                       = C.VK_STRUCTURE_TYPE_IMPORT_SEMAPHORE_WIN32_HANDLE_INFO_KHR
	STRUCTURE_TYPE_EXPORT_SEMAPHORE_WIN32_HANDLE_INFO_KHR                       = C.VK_STRUCTURE_TYPE_EXPORT_SEMAPHORE_WIN32_HANDLE_INFO_KHR
	STRUCTURE_TYPE_D3D12_FENCE_SUBMIT_INFO_KHR                                  = C.VK_STRUCTURE_TYPE_D3D12_FENCE_SUBMIT_INFO_KHR
	STRUCTURE_TYPE_SEMAPHORE_GET_WIN32_HANDLE_INFO_KHR                          = C.VK_STRUCTURE_TYPE_SEMAPHORE_GET_WIN32_HANDLE_INFO_KHR
	STRUCTURE_TYPE_IMPORT_SEMAPHORE_FD_INFO_KHR                                 = C.VK_STRUCTURE_TYPE_IMPORT_SEMAPHORE_FD_INFO_KHR
	STRUCTURE_TYPE_SEMAPHORE_GET_FD_INFO_KHR                                    = C.VK_STRUCTURE_TYPE_SEMAPHORE_GET_FD_INFO_KHR
	STRUCTURE_TYPE_PHYSICAL_DEVICE_PUSH_DESCRIPTOR_PROPERTIES_KHR               = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PUSH_DESCRIPTOR_PROPERTIES_KHR
	STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_CONDITIONAL_RENDERING_INFO_EXT    = C.VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_CONDITIONAL_RENDERING_INFO_EXT
	STRUCTURE_TYPE_PHYSICAL_DEVICE_CONDITIONAL_RENDERING_FEATURES_EXT           = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CONDITIONAL_RENDERING_FEATURES_EXT
	STRUCTURE_TYPE_CONDITIONAL_RENDERING_BEGIN_INFO_EXT                         = C.VK_STRUCTURE_TYPE_CONDITIONAL_RENDERING_BEGIN_INFO_EXT
	STRUCTURE_TYPE_PRESENT_REGIONS_KHR                                          = C.VK_STRUCTURE_TYPE_PRESENT_REGIONS_KHR
	STRUCTURE_TYPE_OBJECT_TABLE_CREATE_INFO_NVX                                 = C.VK_STRUCTURE_TYPE_OBJECT_TABLE_CREATE_INFO_NVX
	STRUCTURE_TYPE_INDIRECT_COMMANDS_LAYOUT_CREATE_INFO_NVX                     = C.VK_STRUCTURE_TYPE_INDIRECT_COMMANDS_LAYOUT_CREATE_INFO_NVX
	STRUCTURE_TYPE_CMD_PROCESS_COMMANDS_INFO_NVX                                = C.VK_STRUCTURE_TYPE_CMD_PROCESS_COMMANDS_INFO_NVX
	STRUCTURE_TYPE_CMD_RESERVE_SPACE_FOR_COMMANDS_INFO_NVX                      = C.VK_STRUCTURE_TYPE_CMD_RESERVE_SPACE_FOR_COMMANDS_INFO_NVX
	STRUCTURE_TYPE_DEVICE_GENERATED_COMMANDS_LIMITS_NVX                         = C.VK_STRUCTURE_TYPE_DEVICE_GENERATED_COMMANDS_LIMITS_NVX
	STRUCTURE_TYPE_DEVICE_GENERATED_COMMANDS_FEATURES_NVX                       = C.VK_STRUCTURE_TYPE_DEVICE_GENERATED_COMMANDS_FEATURES_NVX
	STRUCTURE_TYPE_PIPELINE_VIEWPORT_W_SCALING_STATE_CREATE_INFO_NV             = C.VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_W_SCALING_STATE_CREATE_INFO_NV
	STRUCTURE_TYPE_SURFACE_CAPABILITIES_2_EXT                                   = C.VK_STRUCTURE_TYPE_SURFACE_CAPABILITIES_2_EXT
	STRUCTURE_TYPE_DISPLAY_POWER_INFO_EXT                                       = C.VK_STRUCTURE_TYPE_DISPLAY_POWER_INFO_EXT
	STRUCTURE_TYPE_DEVICE_EVENT_INFO_EXT                                        = C.VK_STRUCTURE_TYPE_DEVICE_EVENT_INFO_EXT
	STRUCTURE_TYPE_DISPLAY_EVENT_INFO_EXT                                       = C.VK_STRUCTURE_TYPE_DISPLAY_EVENT_INFO_EXT
	STRUCTURE_TYPE_SWAPCHAIN_COUNTER_CREATE_INFO_EXT                            = C.VK_STRUCTURE_TYPE_SWAPCHAIN_COUNTER_CREATE_INFO_EXT
	STRUCTURE_TYPE_PRESENT_TIMES_INFO_GOOGLE                                    = C.VK_STRUCTURE_TYPE_PRESENT_TIMES_INFO_GOOGLE
	STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PER_VIEW_ATTRIBUTES_PROPERTIES_NVX = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PER_VIEW_ATTRIBUTES_PROPERTIES_NVX
	STRUCTURE_TYPE_PIPELINE_VIEWPORT_SWIZZLE_STATE_CREATE_INFO_NV               = C.VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_SWIZZLE_STATE_CREATE_INFO_NV
	STRUCTURE_TYPE_PHYSICAL_DEVICE_DISCARD_RECTANGLE_PROPERTIES_EXT             = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DISCARD_RECTANGLE_PROPERTIES_EXT
	STRUCTURE_TYPE_PIPELINE_DISCARD_RECTANGLE_STATE_CREATE_INFO_EXT             = C.VK_STRUCTURE_TYPE_PIPELINE_DISCARD_RECTANGLE_STATE_CREATE_INFO_EXT
	STRUCTURE_TYPE_PHYSICAL_DEVICE_CONSERVATIVE_RASTERIZATION_PROPERTIES_EXT    = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CONSERVATIVE_RASTERIZATION_PROPERTIES_EXT
	STRUCTURE_TYPE_PIPELINE_RASTERIZATION_CONSERVATIVE_STATE_CREATE_INFO_EXT    = C.VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_CONSERVATIVE_STATE_CREATE_INFO_EXT
	STRUCTURE_TYPE_HDR_METADATA_EXT                                             = C.VK_STRUCTURE_TYPE_HDR_METADATA_EXT
	STRUCTURE_TYPE_ATTACHMENT_DESCRIPTION_2_KHR                                 = C.VK_STRUCTURE_TYPE_ATTACHMENT_DESCRIPTION_2_KHR
	STRUCTURE_TYPE_ATTACHMENT_REFERENCE_2_KHR                                   = C.VK_STRUCTURE_TYPE_ATTACHMENT_REFERENCE_2_KHR
	STRUCTURE_TYPE_SUBPASS_DESCRIPTION_2_KHR                                    = C.VK_STRUCTURE_TYPE_SUBPASS_DESCRIPTION_2_KHR
	STRUCTURE_TYPE_SUBPASS_DEPENDENCY_2_KHR                                     = C.VK_STRUCTURE_TYPE_SUBPASS_DEPENDENCY_2_KHR
	STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO_2_KHR                                = C.VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO_2_KHR
	STRUCTURE_TYPE_SUBPASS_BEGIN_INFO_KHR                                       = C.VK_STRUCTURE_TYPE_SUBPASS_BEGIN_INFO_KHR
	STRUCTURE_TYPE_SUBPASS_END_INFO_KHR                                         = C.VK_STRUCTURE_TYPE_SUBPASS_END_INFO_KHR
	STRUCTURE_TYPE_SHARED_PRESENT_SURFACE_CAPABILITIES_KHR                      = C.VK_STRUCTURE_TYPE_SHARED_PRESENT_SURFACE_CAPABILITIES_KHR
	STRUCTURE_TYPE_IMPORT_FENCE_WIN32_HANDLE_INFO_KHR                           = C.VK_STRUCTURE_TYPE_IMPORT_FENCE_WIN32_HANDLE_INFO_KHR
	STRUCTURE_TYPE_EXPORT_FENCE_WIN32_HANDLE_INFO_KHR                           = C.VK_STRUCTURE_TYPE_EXPORT_FENCE_WIN32_HANDLE_INFO_KHR
	STRUCTURE_TYPE_FENCE_GET_WIN32_HANDLE_INFO_KHR                              = C.VK_STRUCTURE_TYPE_FENCE_GET_WIN32_HANDLE_INFO_KHR
	STRUCTURE_TYPE_IMPORT_FENCE_FD_INFO_KHR                                     = C.VK_STRUCTURE_TYPE_IMPORT_FENCE_FD_INFO_KHR
	STRUCTURE_TYPE_FENCE_GET_FD_INFO_KHR                                        = C.VK_STRUCTURE_TYPE_FENCE_GET_FD_INFO_KHR
	STRUCTURE_TYPE_PHYSICAL_DEVICE_SURFACE_INFO_2_KHR                           = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SURFACE_INFO_2_KHR
	STRUCTURE_TYPE_SURFACE_CAPABILITIES_2_KHR                                   = C.VK_STRUCTURE_TYPE_SURFACE_CAPABILITIES_2_KHR
	STRUCTURE_TYPE_SURFACE_FORMAT_2_KHR                                         = C.VK_STRUCTURE_TYPE_SURFACE_FORMAT_2_KHR
	STRUCTURE_TYPE_DISPLAY_PROPERTIES_2_KHR                                     = C.VK_STRUCTURE_TYPE_DISPLAY_PROPERTIES_2_KHR
	STRUCTURE_TYPE_DISPLAY_PLANE_PROPERTIES_2_KHR                               = C.VK_STRUCTURE_TYPE_DISPLAY_PLANE_PROPERTIES_2_KHR
	STRUCTURE_TYPE_DISPLAY_MODE_PROPERTIES_2_KHR                                = C.VK_STRUCTURE_TYPE_DISPLAY_MODE_PROPERTIES_2_KHR
	STRUCTURE_TYPE_DISPLAY_PLANE_INFO_2_KHR                                     = C.VK_STRUCTURE_TYPE_DISPLAY_PLANE_INFO_2_KHR
	STRUCTURE_TYPE_DISPLAY_PLANE_CAPABILITIES_2_KHR                             = C.VK_STRUCTURE_TYPE_DISPLAY_PLANE_CAPABILITIES_2_KHR
	STRUCTURE_TYPE_IOS_SURFACE_CREATE_INFO_MVK                                  = C.VK_STRUCTURE_TYPE_IOS_SURFACE_CREATE_INFO_MVK
	STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK                                = C.VK_STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK
	STRUCTURE_TYPE_DEBUG_UTILS_OBJECT_NAME_INFO_EXT                             = C.VK_STRUCTURE_TYPE_DEBUG_UTILS_OBJECT_NAME_INFO_EXT
	STRUCTURE_TYPE_DEBUG_UTILS_OBJECT_TAG_INFO_EXT                              = C.VK_STRUCTURE_TYPE_DEBUG_UTILS_OBJECT_TAG_INFO_EXT
	STRUCTURE_TYPE_DEBUG_UTILS_LABEL_EXT                                        = C.VK_STRUCTURE_TYPE_DEBUG_UTILS_LABEL_EXT
	STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT                      = C.VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT
	STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT                        = C.VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT
	STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_USAGE_ANDROID                        = C.VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_USAGE_ANDROID
	STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_PROPERTIES_ANDROID                   = C.VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_PROPERTIES_ANDROID
	STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_FORMAT_PROPERTIES_ANDROID            = C.VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_FORMAT_PROPERTIES_ANDROID
	STRUCTURE_TYPE_IMPORT_ANDROID_HARDWARE_BUFFER_INFO_ANDROID                  = C.VK_STRUCTURE_TYPE_IMPORT_ANDROID_HARDWARE_BUFFER_INFO_ANDROID
	STRUCTURE_TYPE_MEMORY_GET_ANDROID_HARDWARE_BUFFER_INFO_ANDROID              = C.VK_STRUCTURE_TYPE_MEMORY_GET_ANDROID_HARDWARE_BUFFER_INFO_ANDROID
	STRUCTURE_TYPE_EXTERNAL_FORMAT_ANDROID                                      = C.VK_STRUCTURE_TYPE_EXTERNAL_FORMAT_ANDROID
	STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_FILTER_MINMAX_PROPERTIES_EXT         = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_FILTER_MINMAX_PROPERTIES_EXT
	STRUCTURE_TYPE_SAMPLER_REDUCTION_MODE_CREATE_INFO_EXT                       = C.VK_STRUCTURE_TYPE_SAMPLER_REDUCTION_MODE_CREATE_INFO_EXT
	STRUCTURE_TYPE_PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_FEATURES_EXT            = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_FEATURES_EXT
	STRUCTURE_TYPE_PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_PROPERTIES_EXT          = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_PROPERTIES_EXT
	STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET_INLINE_UNIFORM_BLOCK_EXT                = C.VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET_INLINE_UNIFORM_BLOCK_EXT
	STRUCTURE_TYPE_DESCRIPTOR_POOL_INLINE_UNIFORM_BLOCK_CREATE_INFO_EXT         = C.VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_INLINE_UNIFORM_BLOCK_CREATE_INFO_EXT
	STRUCTURE_TYPE_SAMPLE_LOCATIONS_INFO_EXT                                    = C.VK_STRUCTURE_TYPE_SAMPLE_LOCATIONS_INFO_EXT
	STRUCTURE_TYPE_RENDER_PASS_SAMPLE_LOCATIONS_BEGIN_INFO_EXT                  = C.VK_STRUCTURE_TYPE_RENDER_PASS_SAMPLE_LOCATIONS_BEGIN_INFO_EXT
	STRUCTURE_TYPE_PIPELINE_SAMPLE_LOCATIONS_STATE_CREATE_INFO_EXT              = C.VK_STRUCTURE_TYPE_PIPELINE_SAMPLE_LOCATIONS_STATE_CREATE_INFO_EXT
	STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLE_LOCATIONS_PROPERTIES_EXT              = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLE_LOCATIONS_PROPERTIES_EXT
	STRUCTURE_TYPE_MULTISAMPLE_PROPERTIES_EXT                                   = C.VK_STRUCTURE_TYPE_MULTISAMPLE_PROPERTIES_EXT
	STRUCTURE_TYPE_IMAGE_FORMAT_LIST_CREATE_INFO_KHR                            = C.VK_STRUCTURE_TYPE_IMAGE_FORMAT_LIST_CREATE_INFO_KHR
	STRUCTURE_TYPE_PHYSICAL_DEVICE_BLEND_OPERATION_ADVANCED_FEATURES_EXT        = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BLEND_OPERATION_ADVANCED_FEATURES_EXT
	STRUCTURE_TYPE_PHYSICAL_DEVICE_BLEND_OPERATION_ADVANCED_PROPERTIES_EXT      = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BLEND_OPERATION_ADVANCED_PROPERTIES_EXT
	STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_ADVANCED_STATE_CREATE_INFO_EXT          = C.VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_ADVANCED_STATE_CREATE_INFO_EXT
	STRUCTURE_TYPE_PIPELINE_COVERAGE_TO_COLOR_STATE_CREATE_INFO_NV              = C.VK_STRUCTURE_TYPE_PIPELINE_COVERAGE_TO_COLOR_STATE_CREATE_INFO_NV
	STRUCTURE_TYPE_PIPELINE_COVERAGE_MODULATION_STATE_CREATE_INFO_NV            = C.VK_STRUCTURE_TYPE_PIPELINE_COVERAGE_MODULATION_STATE_CREATE_INFO_NV
	STRUCTURE_TYPE_VALIDATION_CACHE_CREATE_INFO_EXT                             = C.VK_STRUCTURE_TYPE_VALIDATION_CACHE_CREATE_INFO_EXT
	STRUCTURE_TYPE_SHADER_MODULE_VALIDATION_CACHE_CREATE_INFO_EXT               = C.VK_STRUCTURE_TYPE_SHADER_MODULE_VALIDATION_CACHE_CREATE_INFO_EXT
	STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO_EXT          = C.VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO_EXT
	STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_FEATURES_EXT             = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_FEATURES_EXT
	STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_PROPERTIES_EXT           = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_PROPERTIES_EXT
	STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_ALLOCATE_INFO_EXT   = C.VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_ALLOCATE_INFO_EXT
	STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_LAYOUT_SUPPORT_EXT  = C.VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_LAYOUT_SUPPORT_EXT
	STRUCTURE_TYPE_PIPELINE_VIEWPORT_SHADING_RATE_IMAGE_STATE_CREATE_INFO_NV    = C.VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_SHADING_RATE_IMAGE_STATE_CREATE_INFO_NV
	STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADING_RATE_IMAGE_FEATURES_NV               = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADING_RATE_IMAGE_FEATURES_NV
	STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADING_RATE_IMAGE_PROPERTIES_NV             = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADING_RATE_IMAGE_PROPERTIES_NV
	STRUCTURE_TYPE_PIPELINE_VIEWPORT_COARSE_SAMPLE_ORDER_STATE_CREATE_INFO_NV   = C.VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_COARSE_SAMPLE_ORDER_STATE_CREATE_INFO_NV
	STRUCTURE_TYPE_RAYTRACING_PIPELINE_CREATE_INFO_NVX                          = C.VK_STRUCTURE_TYPE_RAYTRACING_PIPELINE_CREATE_INFO_NVX
	STRUCTURE_TYPE_ACCELERATION_STRUCTURE_CREATE_INFO_NVX                       = C.VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_CREATE_INFO_NVX
	STRUCTURE_TYPE_GEOMETRY_INSTANCE_NVX                                        = C.VK_STRUCTURE_TYPE_GEOMETRY_INSTANCE_NVX
	STRUCTURE_TYPE_GEOMETRY_NVX                                                 = C.VK_STRUCTURE_TYPE_GEOMETRY_NVX
	STRUCTURE_TYPE_GEOMETRY_TRIANGLES_NVX                                       = C.VK_STRUCTURE_TYPE_GEOMETRY_TRIANGLES_NVX
	STRUCTURE_TYPE_GEOMETRY_AABB_NVX                                            = C.VK_STRUCTURE_TYPE_GEOMETRY_AABB_NVX
	STRUCTURE_TYPE_BIND_ACCELERATION_STRUCTURE_MEMORY_INFO_NVX                  = C.VK_STRUCTURE_TYPE_BIND_ACCELERATION_STRUCTURE_MEMORY_INFO_NVX
	STRUCTURE_TYPE_DESCRIPTOR_ACCELERATION_STRUCTURE_INFO_NVX                   = C.VK_STRUCTURE_TYPE_DESCRIPTOR_ACCELERATION_STRUCTURE_INFO_NVX
	STRUCTURE_TYPE_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_INFO_NVX          = C.VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_INFO_NVX
	STRUCTURE_TYPE_PHYSICAL_DEVICE_RAYTRACING_PROPERTIES_NVX                    = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAYTRACING_PROPERTIES_NVX
	STRUCTURE_TYPE_HIT_SHADER_MODULE_CREATE_INFO_NVX                            = C.VK_STRUCTURE_TYPE_HIT_SHADER_MODULE_CREATE_INFO_NVX
	STRUCTURE_TYPE_PHYSICAL_DEVICE_REPRESENTATIVE_FRAGMENT_TEST_FEATURES_NV     = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_REPRESENTATIVE_FRAGMENT_TEST_FEATURES_NV
	STRUCTURE_TYPE_PIPELINE_REPRESENTATIVE_FRAGMENT_TEST_STATE_CREATE_INFO_NV   = C.VK_STRUCTURE_TYPE_PIPELINE_REPRESENTATIVE_FRAGMENT_TEST_STATE_CREATE_INFO_NV
	STRUCTURE_TYPE_DEVICE_QUEUE_GLOBAL_PRIORITY_CREATE_INFO_EXT                 = C.VK_STRUCTURE_TYPE_DEVICE_QUEUE_GLOBAL_PRIORITY_CREATE_INFO_EXT
	STRUCTURE_TYPE_PHYSICAL_DEVICE_8BIT_STORAGE_FEATURES_KHR                    = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_8BIT_STORAGE_FEATURES_KHR
	STRUCTURE_TYPE_IMPORT_MEMORY_HOST_POINTER_INFO_EXT                          = C.VK_STRUCTURE_TYPE_IMPORT_MEMORY_HOST_POINTER_INFO_EXT
	STRUCTURE_TYPE_MEMORY_HOST_POINTER_PROPERTIES_EXT                           = C.VK_STRUCTURE_TYPE_MEMORY_HOST_POINTER_PROPERTIES_EXT
	STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_MEMORY_HOST_PROPERTIES_EXT          = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_MEMORY_HOST_PROPERTIES_EXT
	STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CORE_PROPERTIES_AMD                   = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CORE_PROPERTIES_AMD
	STRUCTURE_TYPE_PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_DIVISOR_PROPERTIES_EXT      = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_DIVISOR_PROPERTIES_EXT
	STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_DIVISOR_STATE_CREATE_INFO_EXT          = C.VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_DIVISOR_STATE_CREATE_INFO_EXT
	STRUCTURE_TYPE_PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_DIVISOR_FEATURES_EXT        = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_DIVISOR_FEATURES_EXT
	STRUCTURE_TYPE_PHYSICAL_DEVICE_COMPUTE_SHADER_DERIVATIVES_FEATURES_NV       = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COMPUTE_SHADER_DERIVATIVES_FEATURES_NV
	STRUCTURE_TYPE_PHYSICAL_DEVICE_MESH_SHADER_FEATURES_NV                      = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MESH_SHADER_FEATURES_NV
	STRUCTURE_TYPE_PHYSICAL_DEVICE_MESH_SHADER_PROPERTIES_NV                    = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MESH_SHADER_PROPERTIES_NV
	STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_SHADER_BARYCENTRIC_FEATURES_NV      = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_SHADER_BARYCENTRIC_FEATURES_NV
	STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_IMAGE_FOOTPRINT_FEATURES_NV           = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_IMAGE_FOOTPRINT_FEATURES_NV
	STRUCTURE_TYPE_PIPELINE_VIEWPORT_EXCLUSIVE_SCISSOR_STATE_CREATE_INFO_NV     = C.VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_EXCLUSIVE_SCISSOR_STATE_CREATE_INFO_NV
	STRUCTURE_TYPE_PHYSICAL_DEVICE_EXCLUSIVE_SCISSOR_FEATURES_NV                = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXCLUSIVE_SCISSOR_FEATURES_NV
	STRUCTURE_TYPE_CHECKPOINT_DATA_NV                                           = C.VK_STRUCTURE_TYPE_CHECKPOINT_DATA_NV
	STRUCTURE_TYPE_QUEUE_FAMILY_CHECKPOINT_PROPERTIES_NV                        = C.VK_STRUCTURE_TYPE_QUEUE_FAMILY_CHECKPOINT_PROPERTIES_NV
	STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_MEMORY_MODEL_FEATURES_KHR             = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_MEMORY_MODEL_FEATURES_KHR
	STRUCTURE_TYPE_DEBUG_REPORT_CREATE_INFO_EXT                                 = C.VK_STRUCTURE_TYPE_DEBUG_REPORT_CREATE_INFO_EXT
	STRUCTURE_TYPE_RENDER_PASS_MULTIVIEW_CREATE_INFO_KHR                        = C.VK_STRUCTURE_TYPE_RENDER_PASS_MULTIVIEW_CREATE_INFO_KHR
	STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_FEATURES_KHR                       = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_FEATURES_KHR
	STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PROPERTIES_KHR                     = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PROPERTIES_KHR
	STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2_KHR                               = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2_KHR
	STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2_KHR                             = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2_KHR
	STRUCTURE_TYPE_FORMAT_PROPERTIES_2_KHR                                      = C.VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_2_KHR
	STRUCTURE_TYPE_IMAGE_FORMAT_PROPERTIES_2_KHR                                = C.VK_STRUCTURE_TYPE_IMAGE_FORMAT_PROPERTIES_2_KHR
	STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2_KHR                      = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2_KHR
	STRUCTURE_TYPE_QUEUE_FAMILY_PROPERTIES_2_KHR                                = C.VK_STRUCTURE_TYPE_QUEUE_FAMILY_PROPERTIES_2_KHR
	STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_PROPERTIES_2_KHR                      = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_PROPERTIES_2_KHR
	STRUCTURE_TYPE_SPARSE_IMAGE_FORMAT_PROPERTIES_2_KHR                         = C.VK_STRUCTURE_TYPE_SPARSE_IMAGE_FORMAT_PROPERTIES_2_KHR
	STRUCTURE_TYPE_PHYSICAL_DEVICE_SPARSE_IMAGE_FORMAT_INFO_2_KHR               = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SPARSE_IMAGE_FORMAT_INFO_2_KHR
	STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO_KHR                               = C.VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO_KHR
	STRUCTURE_TYPE_DEVICE_GROUP_RENDER_PASS_BEGIN_INFO_KHR                      = C.VK_STRUCTURE_TYPE_DEVICE_GROUP_RENDER_PASS_BEGIN_INFO_KHR
	STRUCTURE_TYPE_DEVICE_GROUP_COMMAND_BUFFER_BEGIN_INFO_KHR                   = C.VK_STRUCTURE_TYPE_DEVICE_GROUP_COMMAND_BUFFER_BEGIN_INFO_KHR
	STRUCTURE_TYPE_DEVICE_GROUP_SUBMIT_INFO_KHR                                 = C.VK_STRUCTURE_TYPE_DEVICE_GROUP_SUBMIT_INFO_KHR
	STRUCTURE_TYPE_DEVICE_GROUP_BIND_SPARSE_INFO_KHR                            = C.VK_STRUCTURE_TYPE_DEVICE_GROUP_BIND_SPARSE_INFO_KHR
	STRUCTURE_TYPE_BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO_KHR                     = C.VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO_KHR
	STRUCTURE_TYPE_BIND_IMAGE_MEMORY_DEVICE_GROUP_INFO_KHR                      = C.VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_DEVICE_GROUP_INFO_KHR
	STRUCTURE_TYPE_PHYSICAL_DEVICE_GROUP_PROPERTIES_KHR                         = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GROUP_PROPERTIES_KHR
	STRUCTURE_TYPE_DEVICE_GROUP_DEVICE_CREATE_INFO_KHR                          = C.VK_STRUCTURE_TYPE_DEVICE_GROUP_DEVICE_CREATE_INFO_KHR
	STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_IMAGE_FORMAT_INFO_KHR               = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_IMAGE_FORMAT_INFO_KHR
	STRUCTURE_TYPE_EXTERNAL_IMAGE_FORMAT_PROPERTIES_KHR                         = C.VK_STRUCTURE_TYPE_EXTERNAL_IMAGE_FORMAT_PROPERTIES_KHR
	STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_BUFFER_INFO_KHR                     = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_BUFFER_INFO_KHR
	STRUCTURE_TYPE_EXTERNAL_BUFFER_PROPERTIES_KHR                               = C.VK_STRUCTURE_TYPE_EXTERNAL_BUFFER_PROPERTIES_KHR
	STRUCTURE_TYPE_PHYSICAL_DEVICE_ID_PROPERTIES_KHR                            = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ID_PROPERTIES_KHR
	STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO_KHR                       = C.VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO_KHR
	STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO_KHR                        = C.VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO_KHR
	STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO_KHR                              = C.VK_STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO_KHR
	STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_SEMAPHORE_INFO_KHR                  = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_SEMAPHORE_INFO_KHR
	STRUCTURE_TYPE_EXTERNAL_SEMAPHORE_PROPERTIES_KHR                            = C.VK_STRUCTURE_TYPE_EXTERNAL_SEMAPHORE_PROPERTIES_KHR
	STRUCTURE_TYPE_EXPORT_SEMAPHORE_CREATE_INFO_KHR                             = C.VK_STRUCTURE_TYPE_EXPORT_SEMAPHORE_CREATE_INFO_KHR
	STRUCTURE_TYPE_PHYSICAL_DEVICE_16BIT_STORAGE_FEATURES_KHR                   = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_16BIT_STORAGE_FEATURES_KHR
	STRUCTURE_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_CREATE_INFO_KHR                   = C.VK_STRUCTURE_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_CREATE_INFO_KHR
	STRUCTURE_TYPE_SURFACE_CAPABILITIES2_EXT                                    = C.VK_STRUCTURE_TYPE_SURFACE_CAPABILITIES2_EXT
	STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_FENCE_INFO_KHR                      = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_FENCE_INFO_KHR
	STRUCTURE_TYPE_EXTERNAL_FENCE_PROPERTIES_KHR                                = C.VK_STRUCTURE_TYPE_EXTERNAL_FENCE_PROPERTIES_KHR
	STRUCTURE_TYPE_EXPORT_FENCE_CREATE_INFO_KHR                                 = C.VK_STRUCTURE_TYPE_EXPORT_FENCE_CREATE_INFO_KHR
	STRUCTURE_TYPE_PHYSICAL_DEVICE_POINT_CLIPPING_PROPERTIES_KHR                = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_POINT_CLIPPING_PROPERTIES_KHR
	STRUCTURE_TYPE_RENDER_PASS_INPUT_ATTACHMENT_ASPECT_CREATE_INFO_KHR          = C.VK_STRUCTURE_TYPE_RENDER_PASS_INPUT_ATTACHMENT_ASPECT_CREATE_INFO_KHR
	STRUCTURE_TYPE_IMAGE_VIEW_USAGE_CREATE_INFO_KHR                             = C.VK_STRUCTURE_TYPE_IMAGE_VIEW_USAGE_CREATE_INFO_KHR
	STRUCTURE_TYPE_PIPELINE_TESSELLATION_DOMAIN_ORIGIN_STATE_CREATE_INFO_KHR    = C.VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_DOMAIN_ORIGIN_STATE_CREATE_INFO_KHR
	STRUCTURE_TYPE_PHYSICAL_DEVICE_VARIABLE_POINTER_FEATURES_KHR                = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VARIABLE_POINTER_FEATURES_KHR
	STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS_KHR                            = C.VK_STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS_KHR
	STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO_KHR                           = C.VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO_KHR
	STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2_KHR                        = C.VK_STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2_KHR
	STRUCTURE_TYPE_IMAGE_MEMORY_REQUIREMENTS_INFO_2_KHR                         = C.VK_STRUCTURE_TYPE_IMAGE_MEMORY_REQUIREMENTS_INFO_2_KHR
	STRUCTURE_TYPE_IMAGE_SPARSE_MEMORY_REQUIREMENTS_INFO_2_KHR                  = C.VK_STRUCTURE_TYPE_IMAGE_SPARSE_MEMORY_REQUIREMENTS_INFO_2_KHR
	STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2_KHR                                    = C.VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2_KHR
	STRUCTURE_TYPE_SPARSE_IMAGE_MEMORY_REQUIREMENTS_2_KHR                       = C.VK_STRUCTURE_TYPE_SPARSE_IMAGE_MEMORY_REQUIREMENTS_2_KHR
	STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO_KHR                     = C.VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO_KHR
	STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO_KHR                            = C.VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO_KHR
	STRUCTURE_TYPE_BIND_IMAGE_PLANE_MEMORY_INFO_KHR                             = C.VK_STRUCTURE_TYPE_BIND_IMAGE_PLANE_MEMORY_INFO_KHR
	STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO_KHR                     = C.VK_STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO_KHR
	STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES_KHR        = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES_KHR
	STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES_KHR         = C.VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES_KHR
	STRUCTURE_TYPE_BIND_BUFFER_MEMORY_INFO_KHR                                  = C.VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_INFO_KHR
	STRUCTURE_TYPE_BIND_IMAGE_MEMORY_INFO_KHR                                   = C.VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_INFO_KHR
	STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_3_PROPERTIES_KHR                 = C.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_3_PROPERTIES_KHR
	STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_SUPPORT_KHR                            = C.VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_SUPPORT_KHR
)

const (
	SURFACE_TRANSFORM_IDENTITY_BIT_KHR                     SurfaceTransformFlagsKHR = C.VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR
	SURFACE_TRANSFORM_ROTATE_90_BIT_KHR                    SurfaceTransformFlagsKHR = C.VK_SURFACE_TRANSFORM_ROTATE_90_BIT_KHR
	SURFACE_TRANSFORM_ROTATE_180_BIT_KHR                   SurfaceTransformFlagsKHR = C.VK_SURFACE_TRANSFORM_ROTATE_180_BIT_KHR
	SURFACE_TRANSFORM_ROTATE_270_BIT_KHR                   SurfaceTransformFlagsKHR = C.VK_SURFACE_TRANSFORM_ROTATE_270_BIT_KHR
	SURFACE_TRANSFORM_HORIZONTAL_MIRROR_BIT_KHR            SurfaceTransformFlagsKHR = C.VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_BIT_KHR
	SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR  SurfaceTransformFlagsKHR = C.VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR
	SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR SurfaceTransformFlagsKHR = C.VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR
	SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR SurfaceTransformFlagsKHR = C.VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR
	SURFACE_TRANSFORM_INHERIT_BIT_KHR                      SurfaceTransformFlagsKHR = C.VK_SURFACE_TRANSFORM_INHERIT_BIT_KHR
)

const (
	COMPOSITE_ALPHA_OPAQUE_BIT_KHR          CompositeAlphaFlagsKHR = C.VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR
	COMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR  CompositeAlphaFlagsKHR = C.VK_COMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR
	COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR CompositeAlphaFlagsKHR = C.VK_COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR
	COMPOSITE_ALPHA_INHERIT_BIT_KHR         CompositeAlphaFlagsKHR = C.VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR
)

const (
	IMAGE_USAGE_TRANSFER_SRC_BIT             ImageUsageFlags = C.VK_IMAGE_USAGE_TRANSFER_SRC_BIT
	IMAGE_USAGE_TRANSFER_DST_BIT             ImageUsageFlags = C.VK_IMAGE_USAGE_TRANSFER_DST_BIT
	IMAGE_USAGE_SAMPLED_BIT                  ImageUsageFlags = C.VK_IMAGE_USAGE_SAMPLED_BIT
	IMAGE_USAGE_STORAGE_BIT                  ImageUsageFlags = C.VK_IMAGE_USAGE_STORAGE_BIT
	IMAGE_USAGE_COLOR_ATTACHMENT_BIT         ImageUsageFlags = C.VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT
	IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT ImageUsageFlags = C.VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT
	IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT     ImageUsageFlags = C.VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT
	IMAGE_USAGE_INPUT_ATTACHMENT_BIT         ImageUsageFlags = C.VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT
)

const (
	FORMAT_UNDEFINED                  Format = C.VK_FORMAT_UNDEFINED
	FORMAT_R4G4_UNORM_PACK8           Format = C.VK_FORMAT_R4G4_UNORM_PACK8
	FORMAT_R4G4B4A4_UNORM_PACK16      Format = C.VK_FORMAT_R4G4B4A4_UNORM_PACK16
	FORMAT_B4G4R4A4_UNORM_PACK16      Format = C.VK_FORMAT_B4G4R4A4_UNORM_PACK16
	FORMAT_R5G6B5_UNORM_PACK16        Format = C.VK_FORMAT_R5G6B5_UNORM_PACK16
	FORMAT_B5G6R5_UNORM_PACK16        Format = C.VK_FORMAT_B5G6R5_UNORM_PACK16
	FORMAT_R5G5B5A1_UNORM_PACK16      Format = C.VK_FORMAT_R5G5B5A1_UNORM_PACK16
	FORMAT_B5G5R5A1_UNORM_PACK16      Format = C.VK_FORMAT_B5G5R5A1_UNORM_PACK16
	FORMAT_A1R5G5B5_UNORM_PACK16      Format = C.VK_FORMAT_A1R5G5B5_UNORM_PACK16
	FORMAT_R8_UNORM                   Format = C.VK_FORMAT_R8_UNORM
	FORMAT_R8_SNORM                   Format = C.VK_FORMAT_R8_SNORM
	FORMAT_R8_USCALED                 Format = C.VK_FORMAT_R8_USCALED
	FORMAT_R8_SSCALED                 Format = C.VK_FORMAT_R8_SSCALED
	FORMAT_R8_UINT                    Format = C.VK_FORMAT_R8_UINT
	FORMAT_R8_SINT                    Format = C.VK_FORMAT_R8_SINT
	FORMAT_R8_SRGB                    Format = C.VK_FORMAT_R8_SRGB
	FORMAT_R8G8_UNORM                 Format = C.VK_FORMAT_R8G8_UNORM
	FORMAT_R8G8_SNORM                 Format = C.VK_FORMAT_R8G8_SNORM
	FORMAT_R8G8_USCALED               Format = C.VK_FORMAT_R8G8_USCALED
	FORMAT_R8G8_SSCALED               Format = C.VK_FORMAT_R8G8_SSCALED
	FORMAT_R8G8_UINT                  Format = C.VK_FORMAT_R8G8_UINT
	FORMAT_R8G8_SINT                  Format = C.VK_FORMAT_R8G8_SINT
	FORMAT_R8G8_SRGB                  Format = C.VK_FORMAT_R8G8_SRGB
	FORMAT_R8G8B8_UNORM               Format = C.VK_FORMAT_R8G8B8_UNORM
	FORMAT_R8G8B8_SNORM               Format = C.VK_FORMAT_R8G8B8_SNORM
	FORMAT_R8G8B8_USCALED             Format = C.VK_FORMAT_R8G8B8_USCALED
	FORMAT_R8G8B8_SSCALED             Format = C.VK_FORMAT_R8G8B8_SSCALED
	FORMAT_R8G8B8_UINT                Format = C.VK_FORMAT_R8G8B8_UINT
	FORMAT_R8G8B8_SINT                Format = C.VK_FORMAT_R8G8B8_SINT
	FORMAT_R8G8B8_SRGB                Format = C.VK_FORMAT_R8G8B8_SRGB
	FORMAT_B8G8R8_UNORM               Format = C.VK_FORMAT_B8G8R8_UNORM
	FORMAT_B8G8R8_SNORM               Format = C.VK_FORMAT_B8G8R8_SNORM
	FORMAT_B8G8R8_USCALED             Format = C.VK_FORMAT_B8G8R8_USCALED
	FORMAT_B8G8R8_SSCALED             Format = C.VK_FORMAT_B8G8R8_SSCALED
	FORMAT_B8G8R8_UINT                Format = C.VK_FORMAT_B8G8R8_UINT
	FORMAT_B8G8R8_SINT                Format = C.VK_FORMAT_B8G8R8_SINT
	FORMAT_B8G8R8_SRGB                Format = C.VK_FORMAT_B8G8R8_SRGB
	FORMAT_R8G8B8A8_UNORM             Format = C.VK_FORMAT_R8G8B8A8_UNORM
	FORMAT_R8G8B8A8_SNORM             Format = C.VK_FORMAT_R8G8B8A8_SNORM
	FORMAT_R8G8B8A8_USCALED           Format = C.VK_FORMAT_R8G8B8A8_USCALED
	FORMAT_R8G8B8A8_SSCALED           Format = C.VK_FORMAT_R8G8B8A8_SSCALED
	FORMAT_R8G8B8A8_UINT              Format = C.VK_FORMAT_R8G8B8A8_UINT
	FORMAT_R8G8B8A8_SINT              Format = C.VK_FORMAT_R8G8B8A8_SINT
	FORMAT_R8G8B8A8_SRGB              Format = C.VK_FORMAT_R8G8B8A8_SRGB
	FORMAT_B8G8R8A8_UNORM             Format = C.VK_FORMAT_B8G8R8A8_UNORM
	FORMAT_B8G8R8A8_SNORM             Format = C.VK_FORMAT_B8G8R8A8_SNORM
	FORMAT_B8G8R8A8_USCALED           Format = C.VK_FORMAT_B8G8R8A8_USCALED
	FORMAT_B8G8R8A8_SSCALED           Format = C.VK_FORMAT_B8G8R8A8_SSCALED
	FORMAT_B8G8R8A8_UINT              Format = C.VK_FORMAT_B8G8R8A8_UINT
	FORMAT_B8G8R8A8_SINT              Format = C.VK_FORMAT_B8G8R8A8_SINT
	FORMAT_B8G8R8A8_SRGB              Format = C.VK_FORMAT_B8G8R8A8_SRGB
	FORMAT_A8B8G8R8_UNORM_PACK32      Format = C.VK_FORMAT_A8B8G8R8_UNORM_PACK32
	FORMAT_A8B8G8R8_SNORM_PACK32      Format = C.VK_FORMAT_A8B8G8R8_SNORM_PACK32
	FORMAT_A8B8G8R8_USCALED_PACK32    Format = C.VK_FORMAT_A8B8G8R8_USCALED_PACK32
	FORMAT_A8B8G8R8_SSCALED_PACK32    Format = C.VK_FORMAT_A8B8G8R8_SSCALED_PACK32
	FORMAT_A8B8G8R8_UINT_PACK32       Format = C.VK_FORMAT_A8B8G8R8_UINT_PACK32
	FORMAT_A8B8G8R8_SINT_PACK32       Format = C.VK_FORMAT_A8B8G8R8_SINT_PACK32
	FORMAT_A8B8G8R8_SRGB_PACK32       Format = C.VK_FORMAT_A8B8G8R8_SRGB_PACK32
	FORMAT_A2R10G10B10_UNORM_PACK32   Format = C.VK_FORMAT_A2R10G10B10_UNORM_PACK32
	FORMAT_A2R10G10B10_SNORM_PACK32   Format = C.VK_FORMAT_A2R10G10B10_SNORM_PACK32
	FORMAT_A2R10G10B10_USCALED_PACK32 Format = C.VK_FORMAT_A2R10G10B10_USCALED_PACK32
	FORMAT_A2R10G10B10_SSCALED_PACK32 Format = C.VK_FORMAT_A2R10G10B10_SSCALED_PACK32
	FORMAT_A2R10G10B10_UINT_PACK32    Format = C.VK_FORMAT_A2R10G10B10_UINT_PACK32
	FORMAT_A2R10G10B10_SINT_PACK32    Format = C.VK_FORMAT_A2R10G10B10_SINT_PACK32
	FORMAT_A2B10G10R10_UNORM_PACK32   Format = C.VK_FORMAT_A2B10G10R10_UNORM_PACK32
	FORMAT_A2B10G10R10_SNORM_PACK32   Format = C.VK_FORMAT_A2B10G10R10_SNORM_PACK32
	FORMAT_A2B10G10R10_USCALED_PACK32 Format = C.VK_FORMAT_A2B10G10R10_USCALED_PACK32
	FORMAT_A2B10G10R10_SSCALED_PACK32 Format = C.VK_FORMAT_A2B10G10R10_SSCALED_PACK32
	FORMAT_A2B10G10R10_UINT_PACK32    Format = C.VK_FORMAT_A2B10G10R10_UINT_PACK32
	FORMAT_A2B10G10R10_SINT_PACK32    Format = C.VK_FORMAT_A2B10G10R10_SINT_PACK32
	FORMAT_R16_UNORM                  Format = C.VK_FORMAT_R16_UNORM
	FORMAT_R16_SNORM                  Format = C.VK_FORMAT_R16_SNORM
	FORMAT_R16_USCALED                Format = C.VK_FORMAT_R16_USCALED
	FORMAT_R16_SSCALED                Format = C.VK_FORMAT_R16_SSCALED
	FORMAT_R16_UINT                   Format = C.VK_FORMAT_R16_UINT
	FORMAT_R16_SINT                   Format = C.VK_FORMAT_R16_SINT
	FORMAT_R16_SFLOAT                 Format = C.VK_FORMAT_R16_SFLOAT
	FORMAT_R16G16_UNORM               Format = C.VK_FORMAT_R16G16_UNORM
	FORMAT_R16G16_SNORM               Format = C.VK_FORMAT_R16G16_SNORM
	FORMAT_R16G16_USCALED             Format = C.VK_FORMAT_R16G16_USCALED
	FORMAT_R16G16_SSCALED             Format = C.VK_FORMAT_R16G16_SSCALED
	FORMAT_R16G16_UINT                Format = C.VK_FORMAT_R16G16_UINT
	FORMAT_R16G16_SINT                Format = C.VK_FORMAT_R16G16_SINT
	FORMAT_R16G16_SFLOAT              Format = C.VK_FORMAT_R16G16_SFLOAT
	FORMAT_R16G16B16_UNORM            Format = C.VK_FORMAT_R16G16B16_UNORM
	FORMAT_R16G16B16_SNORM            Format = C.VK_FORMAT_R16G16B16_SNORM
	FORMAT_R16G16B16_USCALED          Format = C.VK_FORMAT_R16G16B16_USCALED
	FORMAT_R16G16B16_SSCALED          Format = C.VK_FORMAT_R16G16B16_SSCALED
	FORMAT_R16G16B16_UINT             Format = C.VK_FORMAT_R16G16B16_UINT
	FORMAT_R16G16B16_SINT             Format = C.VK_FORMAT_R16G16B16_SINT
	FORMAT_R16G16B16_SFLOAT           Format = C.VK_FORMAT_R16G16B16_SFLOAT
	FORMAT_R16G16B16A16_UNORM         Format = C.VK_FORMAT_R16G16B16A16_UNORM
	FORMAT_R16G16B16A16_SNORM         Format = C.VK_FORMAT_R16G16B16A16_SNORM
	FORMAT_R16G16B16A16_USCALED       Format = C.VK_FORMAT_R16G16B16A16_USCALED
	FORMAT_R16G16B16A16_SSCALED       Format = C.VK_FORMAT_R16G16B16A16_SSCALED
	FORMAT_R16G16B16A16_UINT          Format = C.VK_FORMAT_R16G16B16A16_UINT
	FORMAT_R16G16B16A16_SINT          Format = C.VK_FORMAT_R16G16B16A16_SINT
	FORMAT_R16G16B16A16_SFLOAT        Format = C.VK_FORMAT_R16G16B16A16_SFLOAT
	FORMAT_R32_UINT                   Format = C.VK_FORMAT_R32_UINT
	FORMAT_R32_SINT                   Format = C.VK_FORMAT_R32_SINT
	FORMAT_R32_SFLOAT                 Format = C.VK_FORMAT_R32_SFLOAT
	FORMAT_R32G32_UINT                Format = C.VK_FORMAT_R32G32_UINT
	FORMAT_R32G32_SINT                Format = C.VK_FORMAT_R32G32_SINT
	FORMAT_R32G32_SFLOAT              Format = C.VK_FORMAT_R32G32_SFLOAT
	FORMAT_R32G32B32_UINT             Format = C.VK_FORMAT_R32G32B32_UINT
	FORMAT_R32G32B32_SINT             Format = C.VK_FORMAT_R32G32B32_SINT
	FORMAT_R32G32B32_SFLOAT           Format = C.VK_FORMAT_R32G32B32_SFLOAT
	FORMAT_R32G32B32A32_UINT          Format = C.VK_FORMAT_R32G32B32A32_UINT
	FORMAT_R32G32B32A32_SINT          Format = C.VK_FORMAT_R32G32B32A32_SINT
	FORMAT_R32G32B32A32_SFLOAT        Format = C.VK_FORMAT_R32G32B32A32_SFLOAT
	FORMAT_R64_UINT                   Format = C.VK_FORMAT_R64_UINT
	FORMAT_R64_SINT                   Format = C.VK_FORMAT_R64_SINT
	FORMAT_R64_SFLOAT                 Format = C.VK_FORMAT_R64_SFLOAT
	FORMAT_R64G64_UINT                Format = C.VK_FORMAT_R64G64_UINT
	FORMAT_R64G64_SINT                Format = C.VK_FORMAT_R64G64_SINT
	FORMAT_R64G64_SFLOAT              Format = C.VK_FORMAT_R64G64_SFLOAT
	FORMAT_R64G64B64_UINT             Format = C.VK_FORMAT_R64G64B64_UINT
	FORMAT_R64G64B64_SINT             Format = C.VK_FORMAT_R64G64B64_SINT
	FORMAT_R64G64B64_SFLOAT           Format = C.VK_FORMAT_R64G64B64_SFLOAT
	FORMAT_R64G64B64A64_UINT          Format = C.VK_FORMAT_R64G64B64A64_UINT
	FORMAT_R64G64B64A64_SINT          Format = C.VK_FORMAT_R64G64B64A64_SINT
	FORMAT_R64G64B64A64_SFLOAT        Format = C.VK_FORMAT_R64G64B64A64_SFLOAT
	FORMAT_B10G11R11_UFLOAT_PACK32    Format = C.VK_FORMAT_B10G11R11_UFLOAT_PACK32
	FORMAT_E5B9G9R9_UFLOAT_PACK32     Format = C.VK_FORMAT_E5B9G9R9_UFLOAT_PACK32
	FORMAT_D16_UNORM                  Format = C.VK_FORMAT_D16_UNORM
	FORMAT_X8_D24_UNORM_PACK32        Format = C.VK_FORMAT_X8_D24_UNORM_PACK32
	FORMAT_D32_SFLOAT                 Format = C.VK_FORMAT_D32_SFLOAT
	FORMAT_S8_UINT                    Format = C.VK_FORMAT_S8_UINT
	FORMAT_D16_UNORM_S8_UINT          Format = C.VK_FORMAT_D16_UNORM_S8_UINT
	FORMAT_D24_UNORM_S8_UINT          Format = C.VK_FORMAT_D24_UNORM_S8_UINT
	FORMAT_D32_SFLOAT_S8_UINT         Format = C.VK_FORMAT_D32_SFLOAT_S8_UINT
	FORMAT_BC1_RGB_UNORM_BLOCK        Format = C.VK_FORMAT_BC1_RGB_UNORM_BLOCK
	FORMAT_BC1_RGB_SRGB_BLOCK         Format = C.VK_FORMAT_BC1_RGB_SRGB_BLOCK
	FORMAT_BC1_RGBA_UNORM_BLOCK       Format = C.VK_FORMAT_BC1_RGBA_UNORM_BLOCK
	FORMAT_BC1_RGBA_SRGB_BLOCK        Format = C.VK_FORMAT_BC1_RGBA_SRGB_BLOCK
	FORMAT_BC2_UNORM_BLOCK            Format = C.VK_FORMAT_BC2_UNORM_BLOCK
	FORMAT_BC2_SRGB_BLOCK             Format = C.VK_FORMAT_BC2_SRGB_BLOCK
	FORMAT_BC3_UNORM_BLOCK            Format = C.VK_FORMAT_BC3_UNORM_BLOCK
	FORMAT_BC3_SRGB_BLOCK             Format = C.VK_FORMAT_BC3_SRGB_BLOCK
	FORMAT_BC4_UNORM_BLOCK            Format = C.VK_FORMAT_BC4_UNORM_BLOCK
	FORMAT_BC4_SNORM_BLOCK            Format = C.VK_FORMAT_BC4_SNORM_BLOCK
	FORMAT_BC5_UNORM_BLOCK            Format = C.VK_FORMAT_BC5_UNORM_BLOCK
	FORMAT_BC5_SNORM_BLOCK            Format = C.VK_FORMAT_BC5_SNORM_BLOCK
	FORMAT_BC6H_UFLOAT_BLOCK          Format = C.VK_FORMAT_BC6H_UFLOAT_BLOCK
	FORMAT_BC6H_SFLOAT_BLOCK          Format = C.VK_FORMAT_BC6H_SFLOAT_BLOCK
	FORMAT_BC7_UNORM_BLOCK            Format = C.VK_FORMAT_BC7_UNORM_BLOCK
	FORMAT_BC7_SRGB_BLOCK             Format = C.VK_FORMAT_BC7_SRGB_BLOCK
	FORMAT_ETC2_R8G8B8_UNORM_BLOCK    Format = C.VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK
	FORMAT_ETC2_R8G8B8_SRGB_BLOCK     Format = C.VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK
	FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK  Format = C.VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK
	FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK   Format = C.VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK
	FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK  Format = C.VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK
	FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK   Format = C.VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK
	FORMAT_EAC_R11_UNORM_BLOCK        Format = C.VK_FORMAT_EAC_R11_UNORM_BLOCK
	FORMAT_EAC_R11_SNORM_BLOCK        Format = C.VK_FORMAT_EAC_R11_SNORM_BLOCK
	FORMAT_EAC_R11G11_UNORM_BLOCK     Format = C.VK_FORMAT_EAC_R11G11_UNORM_BLOCK
	FORMAT_EAC_R11G11_SNORM_BLOCK     Format = C.VK_FORMAT_EAC_R11G11_SNORM_BLOCK
	FORMAT_ASTC_4x4_UNORM_BLOCK       Format = C.VK_FORMAT_ASTC_4x4_UNORM_BLOCK
	FORMAT_ASTC_4x4_SRGB_BLOCK        Format = C.VK_FORMAT_ASTC_4x4_SRGB_BLOCK
	FORMAT_ASTC_5x4_UNORM_BLOCK       Format = C.VK_FORMAT_ASTC_5x4_UNORM_BLOCK
	FORMAT_ASTC_5x4_SRGB_BLOCK        Format = C.VK_FORMAT_ASTC_5x4_SRGB_BLOCK
	FORMAT_ASTC_5x5_UNORM_BLOCK       Format = C.VK_FORMAT_ASTC_5x5_UNORM_BLOCK
	FORMAT_ASTC_5x5_SRGB_BLOCK        Format = C.VK_FORMAT_ASTC_5x5_SRGB_BLOCK
	FORMAT_ASTC_6x5_UNORM_BLOCK       Format = C.VK_FORMAT_ASTC_6x5_UNORM_BLOCK
	FORMAT_ASTC_6x5_SRGB_BLOCK        Format = C.VK_FORMAT_ASTC_6x5_SRGB_BLOCK
	FORMAT_ASTC_6x6_UNORM_BLOCK       Format = C.VK_FORMAT_ASTC_6x6_UNORM_BLOCK
	FORMAT_ASTC_6x6_SRGB_BLOCK        Format = C.VK_FORMAT_ASTC_6x6_SRGB_BLOCK
	FORMAT_ASTC_8x5_UNORM_BLOCK       Format = C.VK_FORMAT_ASTC_8x5_UNORM_BLOCK
	FORMAT_ASTC_8x5_SRGB_BLOCK        Format = C.VK_FORMAT_ASTC_8x5_SRGB_BLOCK
	FORMAT_ASTC_8x6_UNORM_BLOCK       Format = C.VK_FORMAT_ASTC_8x6_UNORM_BLOCK
	FORMAT_ASTC_8x6_SRGB_BLOCK        Format = C.VK_FORMAT_ASTC_8x6_SRGB_BLOCK
	FORMAT_ASTC_8x8_UNORM_BLOCK       Format = C.VK_FORMAT_ASTC_8x8_UNORM_BLOCK
	FORMAT_ASTC_8x8_SRGB_BLOCK        Format = C.VK_FORMAT_ASTC_8x8_SRGB_BLOCK
	FORMAT_ASTC_10x5_UNORM_BLOCK      Format = C.VK_FORMAT_ASTC_10x5_UNORM_BLOCK
	FORMAT_ASTC_10x5_SRGB_BLOCK       Format = C.VK_FORMAT_ASTC_10x5_SRGB_BLOCK
	FORMAT_ASTC_10x6_UNORM_BLOCK      Format = C.VK_FORMAT_ASTC_10x6_UNORM_BLOCK
	FORMAT_ASTC_10x6_SRGB_BLOCK       Format = C.VK_FORMAT_ASTC_10x6_SRGB_BLOCK
	FORMAT_ASTC_10x8_UNORM_BLOCK      Format = C.VK_FORMAT_ASTC_10x8_UNORM_BLOCK
	FORMAT_ASTC_10x8_SRGB_BLOCK       Format = C.VK_FORMAT_ASTC_10x8_SRGB_BLOCK
	FORMAT_ASTC_10x10_UNORM_BLOCK     Format = C.VK_FORMAT_ASTC_10x10_UNORM_BLOCK
	FORMAT_ASTC_10x10_SRGB_BLOCK      Format = C.VK_FORMAT_ASTC_10x10_SRGB_BLOCK
	FORMAT_ASTC_12x10_UNORM_BLOCK     Format = C.VK_FORMAT_ASTC_12x10_UNORM_BLOCK
	FORMAT_ASTC_12x10_SRGB_BLOCK      Format = C.VK_FORMAT_ASTC_12x10_SRGB_BLOCK
	FORMAT_ASTC_12x12_UNORM_BLOCK     Format = C.VK_FORMAT_ASTC_12x12_UNORM_BLOCK
	FORMAT_ASTC_12x12_SRGB_BLOCK      Format = C.VK_FORMAT_ASTC_12x12_SRGB_BLOCK
)

const (
	COLOR_SPACE_SRGB_NONLINEAR_KHR ColorSpaceKHR = C.VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
)

const (
	PRESENT_MODE_IMMEDIATE_KHR    PresentModeKHR = C.VK_PRESENT_MODE_IMMEDIATE_KHR
	PRESENT_MODE_MAILBOX_KHR      PresentModeKHR = C.VK_PRESENT_MODE_MAILBOX_KHR
	PRESENT_MODE_FIFO_KHR         PresentModeKHR = C.VK_PRESENT_MODE_FIFO_KHR
	PRESENT_MODE_FIFO_RELAXED_KHR PresentModeKHR = C.VK_PRESENT_MODE_FIFO_RELAXED_KHR
)

func (flags DeviceQueueCreateFlags) String() string {
	var props []string
	if (flags & DEVICE_QUEUE_CREATE_PROTECTED_BIT) != 0 {
		props = append(props, "VK_DEVICE_QUEUE_CREATE_PROTECTED_BIT")
	}
	return strings.Join(props, " | ")
}

func (flags QueueFlags) String() string {
	var props []string
	if (flags & QUEUE_GRAPHICS_BIT) != 0 {
		props = append(props, "VK_QUEUE_GRAPHICS_BIT")
	}
	if (flags & QUEUE_COMPUTE_BIT) != 0 {
		props = append(props, "VK_QUEUE_COMPUTE_BIT")
	}
	if (flags & QUEUE_TRANSFER_BIT) != 0 {
		props = append(props, "VK_QUEUE_TRANSFER_BIT")
	}
	if (flags & QUEUE_SPARSE_BINDING_BIT) != 0 {
		props = append(props, "VK_QUEUE_SPARSE_BINDING_BIT")
	}
	if (flags & QUEUE_PROTECTED_BIT) != 0 {
		props = append(props, "VK_QUEUE_PROTECTED_BIT")
	}
	return strings.Join(props, " | ")
}

func (typ PhysicalDeviceType) String() string {
	switch typ {
	case PHYSICAL_DEVICE_TYPE_OTHER:
		return "VK_PHYSICAL_DEVICE_TYPE_OTHER"
	case PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU:
		return "VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU"
	case PHYSICAL_DEVICE_TYPE_DISCRETE_GPU:
		return "VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU"
	case PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU:
		return "VK_PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU"
	case PHYSICAL_DEVICE_TYPE_CPU:
		return "VK_PHYSICAL_DEVICE_TYPE_CPU"
	default:
		return strconv.Itoa(int(typ))
	}
}

func (res Result) Error() string {
	switch res {
	case SUCCESS:
		return "VK_SUCCESS"
	case NOT_READY:
		return "VK_NOT_READY"
	case TIMEOUT:
		return "VK_TIMEOUT"
	case EVENT_SET:
		return "VK_EVENT_SET"
	case EVENT_RESET:
		return "VK_EVENT_RESET"
	case INCOMPLETE:
		return "VK_INCOMPLETE"
	case ERROR_OUT_OF_HOST_MEMORY:
		return "VK_ERROR_OUT_OF_HOST_MEMORY"
	case ERROR_OUT_OF_DEVICE_MEMORY:
		return "VK_ERROR_OUT_OF_DEVICE_MEMORY"
	case ERROR_INITIALIZATION_FAILED:
		return "VK_ERROR_INITIALIZATION_FAILED"
	case ERROR_DEVICE_LOST:
		return "VK_ERROR_DEVICE_LOST"
	case ERROR_MEMORY_MAP_FAILED:
		return "VK_ERROR_MEMORY_MAP_FAILED"
	case ERROR_LAYER_NOT_PRESENT:
		return "VK_ERROR_LAYER_NOT_PRESENT"
	case ERROR_EXTENSION_NOT_PRESENT:
		return "VK_ERROR_EXTENSION_NOT_PRESENT"
	case ERROR_FEATURE_NOT_PRESENT:
		return "VK_ERROR_FEATURE_NOT_PRESENT"
	case ERROR_INCOMPATIBLE_DRIVER:
		return "VK_ERROR_INCOMPATIBLE_DRIVER"
	case ERROR_TOO_MANY_OBJECTS:
		return "VK_ERROR_TOO_MANY_OBJECTS"
	case ERROR_FORMAT_NOT_SUPPORTED:
		return "VK_ERROR_FORMAT_NOT_SUPPORTED"
	case ERROR_FRAGMENTED_POOL:
		return "VK_ERROR_FRAGMENTED_POOL"
	case ERROR_OUT_OF_POOL_MEMORY:
		return "VK_ERROR_OUT_OF_POOL_MEMORY"
	case ERROR_INVALID_EXTERNAL_HANDLE:
		return "VK_ERROR_INVALID_EXTERNAL_HANDLE"
	case ERROR_SURFACE_LOST_KHR:
		return "VK_ERROR_SURFACE_LOST_KHR"
	case ERROR_NATIVE_WINDOW_IN_USE_KHR:
		return "VK_ERROR_NATIVE_WINDOW_IN_USE_KHR"
	case SUBOPTIMAL_KHR:
		return "VK_SUBOPTIMAL_KHR"
	case ERROR_OUT_OF_DATE_KHR:
		return "VK_ERROR_OUT_OF_DATE_KHR"
	case ERROR_INCOMPATIBLE_DISPLAY_KHR:
		return "VK_ERROR_INCOMPATIBLE_DISPLAY_KHR"
	case ERROR_VALIDATION_FAILED_EXT:
		return "VK_ERROR_VALIDATION_FAILED_EXT"
	case ERROR_INVALID_SHADER_NV:
		return "VK_ERROR_INVALID_SHADER_NV"
	// case VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT:
	// 	return "VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT"
	case ERROR_FRAGMENTATION_EXT:
		return "VK_ERROR_FRAGMENTATION_EXT"
	case ERROR_NOT_PERMITTED_EXT:
		return "VK_ERROR_NOT_PERMITTED_EXT"
	default:
		return strconv.Itoa(int(res))
	}
}

func (flags SurfaceTransformFlagsKHR) String() string {
	var out []string
	if (flags & SURFACE_TRANSFORM_IDENTITY_BIT_KHR) != 0 {
		out = append(out, "VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR")
	}
	if (flags & SURFACE_TRANSFORM_ROTATE_90_BIT_KHR) != 0 {
		out = append(out, "VK_SURFACE_TRANSFORM_ROTATE_90_BIT_KHR")
	}
	if (flags & SURFACE_TRANSFORM_ROTATE_180_BIT_KHR) != 0 {
		out = append(out, "VK_SURFACE_TRANSFORM_ROTATE_180_BIT_KHR")
	}
	if (flags & SURFACE_TRANSFORM_ROTATE_270_BIT_KHR) != 0 {
		out = append(out, "VK_SURFACE_TRANSFORM_ROTATE_270_BIT_KHR")
	}
	if (flags & SURFACE_TRANSFORM_HORIZONTAL_MIRROR_BIT_KHR) != 0 {
		out = append(out, "VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_BIT_KHR")
	}
	if (flags & SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR) != 0 {
		out = append(out, "VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR")
	}
	if (flags & SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR) != 0 {
		out = append(out, "VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR")
	}
	if (flags & SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR) != 0 {
		out = append(out, "VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR")
	}
	if (flags & SURFACE_TRANSFORM_INHERIT_BIT_KHR) != 0 {
		out = append(out, "VK_SURFACE_TRANSFORM_INHERIT_BIT_KHR")
	}
	return strings.Join(out, " | ")
}

func (flags CompositeAlphaFlagsKHR) String() string {
	var out []string
	if (flags & COMPOSITE_ALPHA_OPAQUE_BIT_KHR) != 0 {
		out = append(out, "VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR")
	}
	if (flags & COMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR) != 0 {
		out = append(out, "VK_COMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR")
	}
	if (flags & COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR) != 0 {
		out = append(out, "VK_COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR")
	}
	if (flags & COMPOSITE_ALPHA_INHERIT_BIT_KHR) != 0 {
		out = append(out, "VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR")
	}
	return strings.Join(out, " | ")
}

func (flags ImageUsageFlags) String() string {
	var out []string
	if (flags & IMAGE_USAGE_TRANSFER_SRC_BIT) != 0 {
		out = append(out, "VK_IMAGE_USAGE_TRANSFER_SRC_BIT")
	}
	if (flags & IMAGE_USAGE_TRANSFER_DST_BIT) != 0 {
		out = append(out, "VK_IMAGE_USAGE_TRANSFER_DST_BIT")
	}
	if (flags & IMAGE_USAGE_SAMPLED_BIT) != 0 {
		out = append(out, "VK_IMAGE_USAGE_SAMPLED_BIT")
	}
	if (flags & IMAGE_USAGE_STORAGE_BIT) != 0 {
		out = append(out, "VK_IMAGE_USAGE_STORAGE_BIT")
	}
	if (flags & IMAGE_USAGE_COLOR_ATTACHMENT_BIT) != 0 {
		out = append(out, "VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT")
	}
	if (flags & IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT) != 0 {
		out = append(out, "VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT")
	}
	if (flags & IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT) != 0 {
		out = append(out, "VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT")
	}
	return strings.Join(out, " | ")
}
