// Code generated by "stringer -type=ImageViewType"; DO NOT EDIT.

package vk

import "strconv"

const _ImageViewType_name = "ImageViewType1DImageViewType2DImageViewType3DImageViewTypeCubeImageViewType1DArrayImageViewType2DArrayImageViewTypeCubeArray"

var _ImageViewType_index = [...]uint8{0, 15, 30, 45, 62, 82, 102, 124}

func (i ImageViewType) String() string {
	if i >= ImageViewType(len(_ImageViewType_index)-1) {
		return "ImageViewType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ImageViewType_name[_ImageViewType_index[i]:_ImageViewType_index[i+1]]
}
