// Code generated by "stringer -type=PhysicalDeviceType"; DO NOT EDIT.

package vk

import "strconv"

const _PhysicalDeviceType_name = "PhysicalDeviceTypeOtherPhysicalDeviceTypeIntegratedGPUPhysicalDeviceTypeDiscreteGPUPhysicalDeviceTypeVirtualGPUPhysicalDeviceTypeCPU"

var _PhysicalDeviceType_index = [...]uint8{0, 23, 54, 83, 111, 132}

func (i PhysicalDeviceType) String() string {
	if i >= PhysicalDeviceType(len(_PhysicalDeviceType_index)-1) {
		return "PhysicalDeviceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PhysicalDeviceType_name[_PhysicalDeviceType_index[i]:_PhysicalDeviceType_index[i+1]]
}
