// Code generated by "stringer -type=PresentModeKHR"; DO NOT EDIT.

package vk

import "strconv"

const (
	_PresentModeKHR_name_0 = "PresentModeImmediateKHRPresentModeMailboxKHRPresentModeFifoKHRPresentModeFifoRelaxedKHR"
	_PresentModeKHR_name_1 = "PresentModeSharedDemandRefreshKHRPresentModeSharedContinuousRefreshKHR"
)

var (
	_PresentModeKHR_index_0 = [...]uint8{0, 23, 44, 62, 87}
	_PresentModeKHR_index_1 = [...]uint8{0, 33, 70}
)

func (i PresentModeKHR) String() string {
	switch {
	case 0 <= i && i <= 3:
		return _PresentModeKHR_name_0[_PresentModeKHR_index_0[i]:_PresentModeKHR_index_0[i+1]]
	case 1000111000 <= i && i <= 1000111001:
		i -= 1000111000
		return _PresentModeKHR_name_1[_PresentModeKHR_index_1[i]:_PresentModeKHR_index_1[i+1]]
	default:
		return "PresentModeKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
