// Code generated by "stringer -type=SharingMode"; DO NOT EDIT.

package vk

import "strconv"

const _SharingMode_name = "SharingModeExclusiveSharingModeConcurrent"

var _SharingMode_index = [...]uint8{0, 20, 41}

func (i SharingMode) String() string {
	if i >= SharingMode(len(_SharingMode_index)-1) {
		return "SharingMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SharingMode_name[_SharingMode_index[i]:_SharingMode_index[i+1]]
}
